name: web-ssr
services:
  - name: web-ssr
    type: web
    build:
      type: dockerfile
      dockerfile_path: ./Dockerfile
    ports:
      - port: 8080
        http_path: /
    health_checks:
      - type: tcp
        port: 8080
        interval: 30s
        timeout: 5s
        retries: 3
    env:
      - key: NODE_ENV
        value: production
